#!/bin/bash
FILE=~/scripts/bluetoothDevices.txt

bluetooth_reconnect() {
  {
    sleep 2
    echo "remove $1"
    sleep 2
    echo "power on"
    sleep 2
    echo "scan on"
    sleep 10
    echo -e "pair $1\ntrust $1\nconnect $1"
    sleep 5
    echo "exit"
  } | bluetoothctl
}

if [ ${1,,} == '-h' ] || [ ${1,,} == '--help' ]; then
  echo -e "\nFor reconnecting all bluetooth devices from bluetoothDevices.txt:\n $0\n"
  echo -e "For multiple devices:\n $0 [DEVICES MAC ADDRESSES]\n"
  echo -e "For appending move devices in list:\n $0 -a [DEVICES MAC ADDRESSES]\n"
  echo -e "For listing all devices:\n$0 list OR $0 devices\n"
  echo -e "Devices list is stored at:\n~/scripts/bluetoothDevices.txt\n"
  echo -e "NOTE: NEVER USE APPEND DEVICES COMMAND WHEN LIST IS EMPTY\nALWAYS INITIALIZE WITH FIRST ADDING DEVICES RATHER THEN APPENDING THEM\nIF NOT CAREFULL, SCRIPT WILL MALFUNCTION AND START CONNECTING TO EMPTY DEVICES WHICH WILL JUST CONSUME TIME FOR NO REASON\n"

elif [ ${1,,} == 'list' ] || [ ${1,,} == 'devices' ]; then
  if [ ! -f $FILE ]; then
    echo ""
  else
    cat $FILE
  fi

elif [ $# -eq 0 ]; then
  cat "$FILE"
  while IFS= read -r device || [[ -n "$device" ]]; do
    bluetooth_reconnect "$device"
  done < "$FILE"

else
  if [ ! -f $FILE ]; then
    touch $FILE
  fi
  
  if [ $1 == '-a' ]; then
    if [ $2 == '']; then
      echo "provide MAC addresses to append in blueloothDevices.txt list"
    else
      for (( i=1;i<=$#;i++ )); do
        echo ${!i} >> $FILE
      done
    fi
  else
    echo $1 > $FILE
    for (( i=2;i<=$#;i++ )); do
      echo ${!i} >> $FILE
    done
  fi
fi
